ARG image=scratch
FROM $image
COPY extrafingerprinthelper /.extrafingerprinthack
FROM alpine
COPY --from=0 /data /data
COPY --from=0 /.extrafingerprint* /
RUN rm -f /.extrafingerprinthack
ENV FINGERPRINT_SKIP_ALPINE=TRUE
