#!/bin/bash
# This script builds the container.
# It adds a fingerprint and revision automatically.
# You can pass extra arguments to the script to pass them to the docker build.
# You can also:
#   * prefix the generated tag by setting PREFIX
#   * auto prefix via rpm version by setting:
#     * AUTO_PREFIX="rpm-version-release" and AUTO_PREFIX_PACKAGE=<rpmname>
#   * NEW_BUILD=<anything> will force a new build reguardless of fingerprints.
#       Used for bottstrapping.
# It needs the following variables set:
#   * IMAGE_NAME - the full image name for the latest build.
#   * DOCKER_TAG - the tag the latest build will get.
#   * DOCKER_REPO - the repo the builds will go into.

set -e

echo "Build hook running"
docker build -t tmp$$:1 . "$@"

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/" && pwd )"
. $DIR/../common.sh

setupjq

if [ "x$PREFIX" == "x" ]; then
        if [ "x$AUTO_PREFIX" == "xrpm-version-release" ]; then
                PREFIX=$(docker run -i --rm tmp$$:1 rpm -q --queryformat '%{Version}-%{Release}' "$AUTO_PREFIX_PACKAGE")
        fi
fi

echo "PREFIX determined to be: $PREFIX"

echo "Adding fingerprint."
hubbuildtools/addfingerprint.sh tmp$$:1 tmp$$:2

# Fails if already uploaded to prevent a new version of the same contents
# from landing.
echo "Checking if this version already exists."
hubbuildtools/hubcompare.sh "$DOCKER_REPO" "$DOCKER_TAG" tmp$$:2

echo "Adding revision."
hubbuildtools/addrevision.sh tmp$$:2 "$DOCKER_REPO" "$DOCKER_TAG" "$IMAGE_NAME" "$PREFIX"

docker rmi tmp$$:1 tmp$$:2
