#!/bin/bash -xe
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/" && pwd )"
. $DIR/../common.sh

REGNAME=${REGNAME:=library/registry}

buildregistry
stopregistry
$DIR/../buildquine.sh
docker build -t quine-registry -f $DIR/../Dockerfile.quine .
docker run -d -p 6000:5000 --name quine-registry quine-registry

#FIXME what prefix to use? we need it to be unique in the registry....
docker pull localhost:6000:library/quine-registry
docker rm -f quine-registry
docker tag localhost:6000:library/quine-registry "$IMAGE_NAME"
